### ISSUE TITLE
Disable dated production lists

### ISSUE THREAD

**Issue by mjung** [ox-it/munki-staging#3]
The information when a package moves between catalogues is encapsulated in the meta data of a Trello card. I would like to be able to disable the large amount of dated lists for production and only have one production list.

**Comment by oucsaw** [comment]
Implemented in branch add_option_to_remove_dated_production_list of https://github.com/oucsaw/munki-trello (along with an option to change the date format).

Pull request sent upstream

To use you need to unset `--prod-suffix` and set `--prod-list` if using non-default names

**Comment by mjung** [comment]
On 26 June 2015 at 11:09, Aaron Wilson notifications@github.com wrote:

> Implemented in branch add_option_to_remove_dated_production_list of https://github.com/oucsaw/munki-trello (along with an option to change the date format).
> Pull request sent upstream

Very well done.

> To use you need to unset --prod-suffix and set --prod-list if using non-default names

I assume you just mean --suffix? Code and documentation makes me
assume that. I personally would have preferred a --prod-suffix, but I
might be confused.

M

**Comment by oucsaw** [comment]
On Fri, Jun 26, 2015 at 06:12:12AM -0700, Marko J wrote:

> > To use you need to unset --prod-suffix and set --prod-list if using non-default names
> 
> I assume you just mean --suffix? Code and documentation makes me
> assume that. I personally would have preferred a --prod-suffix, but I
> might be confused.

Innocent look.

The patch changes:

   [line 267]
   o.add_option("--suffix",

to

   [line 267]
   o.add_option("--prod-suffix", "--suffix",

so both will work. 

This is partly as I started out trying to change it so that each
section could be dated or not as the users would like.  However, this
idea has been put on hold/aborted as the script then checks the trello
lists against the catalogs for testing and development, and I couldn't
think of a non-icky way of doing this. However, when the retired
things come along in issue #4 I suspect this will become resolved,

**Comment by oucsaw** [comment]
Changes merged from upstream
